### PR TITLE
install and setup requirements for source and rpm builds

### PR DESCRIPTION
**Pull request by mbacchi**
This prevents the error I was seeing in which pbr_json couldn't be imported.  Also resolve issue 30 opened by gholms so we don't require argparse if python == 2.7.

### CODE REVIEW

**Comment by euca-qa-gui-tester** [comment]
Can one of the admins verify this patch?

**Comment by euca-qa-gui-tester** [comment]
Can one of the admins verify this patch?

**Comment by euca-qa-gui-tester** [comment]
Can one of the admins verify this patch?

**Comment by tbeckham** [comment]
ok to test

**Comment by tbeckham** [comment]
test this please

**Comment by tbeckham** [comment]
test this please

**Pull request merged**
