### PR TITLE
ssh connection checks

### PR DESCRIPTION
**Pull request by ccassler**
Checking ssh connections using ssh_hosts.py instead of checking icmp requests with pinghosts.py

### CODE REVIEW

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com/job/Calyptos%20PR%20Monitor/52/
Test PASSed.

**Comment by tbeckham** [comment]
Thanks @ccassler. Do you think you can look into the possibility of having user and password for the login as parameters?

**Comment by ccassler** [comment]
@tbeckham:  I added user/password as login parameters.

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com/job/Calyptos%20PR%20Monitor/53/
Test FAILed.

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com/job/Calyptos%20PR%20Monitor/54/
Test PASSed.

**Comment by tbeckham** [comment]
ok to test

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com/job/Calyptos%20PR%20Monitor/65/
Test FAILed.

**Comment by tbeckham** [comment]
retest this please

**Comment by euca-qa-gui-tester** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.qa1.eucalyptus-systems.com/job/Calyptos%20PR%20Monitor/66/
Test FAILed.

**Pull request closed without merging**
